
version: "3.9"  # optional since v1.27.0
 
# service - port
# app - 19000
# ??DB?? - 19001
# mock smtp - 19002
# mock cas - 19003
# selenium - 19004

services: 
  openssh-server:
    build: .
    container_name: openssh-server
    hostname: openssh-server #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - PUBLIC_KEY=yourpublickey #optional
      - PUBLIC_KEY_FILE=/path/to/file #optional
      - PUBLIC_KEY_DIR=/path/to/directory/containing/_only_/pubkeys #optional
      - PUBLIC_KEY_URL=https://github.com/username.keys #optional
      - SUDO_ACCESS=true #optional
      - PASSWORD_ACCESS=true #optional
      - USER_PASSWORD=password #optional 
      - USER_NAME=apc #optional
    volumes:
      - /path/to/appdata/config:/config
      - ./commands:/usr/local/bin
      - ./profile:/etc/profile
    ports:
      - 2222:2222
    restart: unless-stopped
